name: Reusable Build

on:
  workflow_call:
    inputs:
      APP_NAME:
          description: 'The name of the application'
          required: false
          type: string

jobs:
  build:
    name: Reusable Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - shell: bash
        run: |
          echo 'build'