name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      script:
        description: "JavaScript function as string"
        required: true
        type: string

jobs:

  eval:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run-script.outputs.result }}
    steps:
      - name: set env
        id: set-env
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Run user script in node and write output
        id: run-script
        env:
          USER_SCRIPT: ${{ inputs.script }}
        run: |
          node -e "
            const fs = require('fs');
            const func = eval('(' + process.env.USER_SCRIPT + ')');
            const result = func({ env: process.env });
            const serialized = typeof result === "string" ? result : JSON.stringify(result);
            const safeValue = serialized.replace(/\n/g, "%0A").replace(/\r/g, "%0D");
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `result=${safeValue}\n`);
          "

  notify:
    runs-on: ubuntu-latest
    needs: [eval]
    steps:
      - name : Notify Deployment
        shell: bash
        run: |
          echo "Deployment result: ${{ needs.eval.outputs.result }}"