name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      script:
        description: "JavaScript function as string"
        required: true
        type: string

jobs:

  eval:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run-script.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: set env
        id: set-env
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Run Script
        id: run-script
        uses: ./.github/actions/gen-matrix
        env:
          test: "test"
        with:
          script: ${{ inputs.script }}

  notify:
    runs-on: ubuntu-latest
    needs: [eval]
    steps:
      - name : Notify Deployment
        shell: bash
        run: |
          echo "Deployment result: ${{ needs.eval.outputs.result }}"