name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      ENV_CONFIG_FILE:
        description: "Path to the environment configuration file"
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name : Notify Deployment
        shell: bash
        run: |
          echo "[Debug] Current directory:"
          pwd
          
          # Set environment variables; default to empty string if not provided
          export HYPHEN_BRANCH="${BRANCH_NAME:+-$BRANCH_NAME}"

          # Log values for debugging
          echo "HYPHEN_BRANCH: $HYPHEN_BRANCH"

          # Show the original .env file content
          echo "[Replace] Before envsubst:"
          cat "./${{ inputs.ENV_CONFIG_FILE }}"

          # Replace placeholders in the file using envsubst
          envsubst < "${{ inputs.ENV_CONFIG_FILE }}" > "${{ inputs.ENV_CONFIG_FILE }}.tmp"
          mv "${{ inputs.ENV_CONFIG_FILE }}.tmp" "${{ inputs.ENV_CONFIG_FILE }}"

          # Show the final content after substitution
          echo "[Replace] After envsubst:"
          cat "${{ inputs.ENV_CONFIG_FILE }}"