name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:

  eval:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run-script.outputs.result }}
    steps:
      - name: set env
        id: set-env
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Write script file
        env:
          APP_NAME: "123"
        run: |
          result=$(node -e "
            const userFunc = ${{ inputs.script }};
            const output = userFunc({ env: process.env });
            console.log(output);
          ")
          echo "result=$result"
          echo "result=$result" >> $GITHUB_OUTPUT

  notify:
    runs-on: ubuntu-latest
    needs: [eval]
    steps:
      - name : Notify Deployment
        shell: bash
        run: |
          echo "Deployment result: ${{ needs.eval.outputs.result }}"