name: test
on:
  workflow_dispatch:
  push:
    branches:
      main

env:
  ENV_NAME: production

jobs:
  release:
    uses: ./.github/workflows/reusable.yml
    with:
      script: |
        ({ env }) =>{
          const APP_NAME = 'decode-portal';
          const IMAGE_NAME = `decode-core-hub/${APP_NAME}`;
          return { APP_NAME, IMAGE_NAME, BRANCH_NAME: env.BRANCH_NAME };
        } 
