name: test
on:
  workflow_dispatch:
  push:
    branches:
      main

env:
  ENV_NAME: production

jobs:
  release:
    uses: ./.github/workflows/reusable.yml
    with:
      script: |
        function ({ env }) {
          console.log('Running script with env:', env
          return { name: 'production', appName: env.APP_NAME, imageTag: env.IMAGE_TAG };
        }
