name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      APP_NAME:
          description: 'The name of the application'
          required: false
          type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml